channels:
  - conda-forge
  - rdkit
dependencies:
  - python>=3.7.0,<3.8
  - pandoc
  - rdkit
  - pip
  - pip:
    - ipython
    - wheel
    - lxml
    - numba
    - numpy
    - sphinx_rtd_theme
    - nbsphinx
    - .
